version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
