language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - CRYPTOGRAPHY_VERSION=2.2.2 # Most recent versions on pip
  - CRYPTOGRAPHY_VERSION=2     # The first version supporting AESGCM

install:
  - pip install cryptography==$CRYPTOGRAPHY_VERSION
  - pip install pytest
  - python setup.py install
  - pip install omemo-backend-signal

script: py.test
